name: Publish package to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish to GitHub Packages
        run: mvn --batch-mode -DuseGithub deploy
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}